version: "3"

services:

  master:
    container_name: master
    build:
      context: ./master
      dockerfile: Dockerfile.dev
    user: root
    hostname: master
    ports:
      - 8080:8080
    volumes:
      - ./jenkins_home:/var/jenkins_home
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

